import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toastify } from "@/components/toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PayMyCoffe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className + ' bg-zinc-200'}
      // style={{backgroundImage:`url(${bgCoffe.src})`}}
      >
        <Toastify />
        {children}
      </body>

    </html>
  );
}
